# Generated by Django 3.1.2 on 2020-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=256)),
                ('pswd', models.CharField(max_length=256)),
            ],
        ),
    ]
